# Don't print a new line at the start of the prompt
add_newline = false

[aws]
disabled = true

[character]
format = "â¯â¯ "
success_symbol = "â¯â¯(bold green) "
error_symbol = "â¯â¯(bold red) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "â€¦/"

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[git_status]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Enable the Kubernetes module
[kubernetes]
disabled = true

[cmd_duration]
min_time = 10_000 # Show command duration over 10,000 milliseconds (=10 sec)
format = " took $duration"

#[git_branch]
#symbol = "ğŸ’» "
#truncation_length = 50
#truncation_symbol = "â€¦"
#style="bold purple"

[hostname]
ssh_only = true
format = "<$hostname>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

#[julia]
#format = "$symbol$version "
#symbol = "à®ƒ "
#style = "bold green"

#[rust]
#format = "via [âš™ï¸ $version](red bold)"

#[python]
#pyenv_version_name = true

#[nodejs]
#format = "via [ğŸ¤– $version](bold green) "

[username]
style_user = "bold dimmed blue"
show_always = false